

- name: daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
    
- name: start and enable backend service
  ansible.builtin.service:
    name: backend
    state: restarted
    enabled: yes